"""
Behavioral Feature Engineering
================================

Computes behavioral features for each UPI transaction, derived entirely
from the sender's own transaction history *up to and excluding* the
current transaction.

This causality constraint is deliberate: in the real-time system this
project is building toward (Phase 8+), a transaction is scored the
moment it happens, using only what is knowable at that instant — the
sender's past behavior, not the future. Computing features this way now
means the feature logic here can be reused later against a live
Kafka/Redis-backed store without having to be rewritten.

For the same reason, this module does **not** reuse the `is_new_device`
/ `is_new_receiver` labels that exist in the raw simulated data. Those
columns were generated by the simulator as ground truth about how each
row was created, but a real system has no access to that — it only has
the historical log. So this module independently *derives* device,
location, and receiver novelty from transaction history, which is a
more realistic basis for model features (and a useful cross-check
against the simulator's own labels during EDA).

Output: one row per input transaction, with the original columns plus
the behavioral feature columns listed in `FEATURE_COLUMNS` below.

Usage:
    python src/features/behavioral_features.py \
        --input data/raw/synthetic_transactions.csv \
        --output data/processed/behavioral_features.csv
"""

from __future__ import annotations

import argparse

import numpy as np
import pandas as pd

SENDER_COL = "sender_upi_id"
TIME_COL = "timestamp"

FEATURE_COLUMNS = [
    "sender_prior_txn_count",
    "sender_avg_amount_prior",
    "sender_std_amount_prior",
    "amount_zscore_vs_sender",
    "amount_ratio_vs_sender_avg",
    "seconds_since_last_txn",
    "sender_txn_count_last_1h",
    "sender_txn_count_last_24h",
    "device_seen_count_prior",
    "is_new_device_derived",
    "location_seen_count_prior",
    "is_new_location_derived",
    "receiver_seen_count_prior",
    "is_new_receiver_derived",
    "sender_typical_hour_prior",
    "hour_deviation_from_typical",
]


def _add_amount_stats(df: pd.DataFrame) -> pd.DataFrame:
    """Rolling count/mean/std of the sender's amount history, prior to each row."""
    g = df.groupby(SENDER_COL)["amount"]

    df["sender_prior_txn_count"] = g.cumcount()
    df["sender_avg_amount_prior"] = g.apply(lambda s: s.expanding().mean().shift(1)).reset_index(level=0, drop=True)
    df["sender_std_amount_prior"] = g.apply(lambda s: s.expanding().std().shift(1)).reset_index(level=0, drop=True)

    # z-score of current amount vs sender's prior distribution.
    # Undefined (NaN) when there's no prior history or prior std is 0/NaN —
    # left as NaN rather than filled, so downstream modeling can treat
    # "insufficient history" as its own signal (via sender_prior_txn_count).
    safe_std = df["sender_std_amount_prior"].replace(0, np.nan)
    df["amount_zscore_vs_sender"] = (df["amount"] - df["sender_avg_amount_prior"]) / safe_std

    safe_avg = df["sender_avg_amount_prior"].replace(0, np.nan)
    df["amount_ratio_vs_sender_avg"] = df["amount"] / safe_avg

    return df


def _add_recency_and_velocity(df: pd.DataFrame) -> pd.DataFrame:
    """Time since the sender's last transaction, and transaction counts in trailing windows."""
    df["seconds_since_last_txn"] = (
        df.groupby(SENDER_COL)[TIME_COL].diff().dt.total_seconds()
    )

    counts_1h = []
    counts_24h = []
    for _, g in df.groupby(SENDER_COL):
        g_indexed = g.set_index(TIME_COL)
        c1h = g_indexed["amount"].rolling("1h").count() - 1  # exclude current row
        c24h = g_indexed["amount"].rolling("24h").count() - 1
        counts_1h.append(pd.Series(c1h.values, index=g.index))
        counts_24h.append(pd.Series(c24h.values, index=g.index))

    df["sender_txn_count_last_1h"] = pd.concat(counts_1h).reindex(df.index)
    df["sender_txn_count_last_24h"] = pd.concat(counts_24h).reindex(df.index)

    return df


def _add_novelty_features(df: pd.DataFrame) -> pd.DataFrame:
    """Independently derive device / location / receiver novelty from history."""
    for col, prefix in [
        ("device_id", "device"),
        ("location", "location"),
        ("receiver_upi_id", "receiver"),
    ]:
        seen_count_prior = df.groupby([SENDER_COL, col]).cumcount()
        df[f"{prefix}_seen_count_prior"] = seen_count_prior
        df[f"is_new_{prefix}_derived"] = seen_count_prior == 0

    return df


def _add_hour_deviation(df: pd.DataFrame) -> pd.DataFrame:
    """How far the current transaction's hour is from the sender's typical hour so far."""
    g = df.groupby(SENDER_COL)["hour_of_day"]
    df["sender_typical_hour_prior"] = g.apply(lambda s: s.expanding().mean().shift(1)).reset_index(level=0, drop=True)

    raw_diff = (df["hour_of_day"] - df["sender_typical_hour_prior"]).abs()
    # hours are circular (0 and 23 are adjacent) — take the shorter distance around the clock
    df["hour_deviation_from_typical"] = np.minimum(raw_diff, 24 - raw_diff)

    return df


def build_features(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df[TIME_COL] = pd.to_datetime(df[TIME_COL])
    df = df.sort_values([SENDER_COL, TIME_COL]).reset_index(drop=True)

    df = _add_amount_stats(df)
    df = _add_recency_and_velocity(df)
    df = _add_novelty_features(df)
    df = _add_hour_deviation(df)

    # Restore original chronological (not sender-grouped) order for output
    df = df.sort_values(TIME_COL).reset_index(drop=True)
    return df


def print_summary(df: pd.DataFrame) -> None:
    print("Feature coverage (non-null %):")
    for col in FEATURE_COLUMNS:
        pct = df[col].notna().mean()
        print(f"  {col:35s} {pct:6.1%}")

    print("\nMean feature values by fraud label:")
    print(df.groupby("label_is_fraud")[FEATURE_COLUMNS].mean().T.to_string())

    print("\nDerived vs. simulator-labeled novelty agreement:")
    device_match = (df["is_new_device_derived"] == df["is_new_device"]).mean()
    receiver_match = (df["is_new_receiver_derived"] == df["is_new_receiver"]).mean()
    print(f"  is_new_device_derived == is_new_device:     {device_match:.1%}")
    print(f"  is_new_receiver_derived == is_new_receiver: {receiver_match:.1%}")


def main():
    parser = argparse.ArgumentParser(description="Build behavioral features for UPI transactions.")
    parser.add_argument("--input", type=str, default="data/raw/synthetic_transactions.csv")
    parser.add_argument("--output", type=str, default="data/processed/behavioral_features.csv")
    args = parser.parse_args()

    raw = pd.read_csv(args.input)
    features = build_features(raw)
    features.to_csv(args.output, index=False)

    print(f"Wrote {len(features)} rows with {len(FEATURE_COLUMNS)} behavioral features to {args.output}\n")
    print_summary(features)


if __name__ == "__main__":
    main()
